# Generated by Django 4.0.4 on 2022-05-08 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0002_alter_device_is_active_alter_location_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='location_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
