# Generated by Django 4.0.4 on 2022-05-08 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0004_location_address_location_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.AddField(
            model_name='device',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='location_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
