# Generated by Django 4.0.4 on 2022-05-23 02:42

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_location_latitude_location_longitude_alter_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InverterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('iemi', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('sid', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('uid', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('rcnt', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('daily_energy', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('total_energy', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('op_active_power', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('specific_yields', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('inverter_op_active_power', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('inverter_daily_energy', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('inverter_total_energy', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('meter_active_power', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InverterJsonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('data', jsonfield.fields.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
