# Generated by Django 4.0.4 on 2022-05-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_inverterdata_inverterjsondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverterdata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inverterjsondata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
