# Generated by Django 4.0.4 on 2022-05-23 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_inverterdata_is_active_inverterjsondata_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inverterdata',
            old_name='iemi',
            new_name='imei',
        ),
    ]
