# Generated by Django 4.0.4 on 2022-05-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_rename_iemi_inverterdata_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='imei',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inverterdata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.device'),
        ),
    ]
