# Generated by Django 4.0.4 on 2022-05-30 09:45

from django.db import migrations, models
import src.base.validators.form_validations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_device_imei_inverterdata_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.IntegerField(choices=[(1, 'DAILY'), (2, 'MONTHLY'), (3, 'YEARLY')], default=1)),
                ('category', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('zip_file', models.FileField(blank=True, max_length=80, null=True, upload_to='reports/%Y/%m/%d', validators=[src.base.validators.form_validations.file_extension_validator])),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ManyToManyField(blank=True, null=True, to='adminapp.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
