# Generated by Django 4.0.4 on 2022-05-31 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0012_zipreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zipreport',
            name='frequency',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
