# Generated by Django 4.0.4 on 2022-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_zipreport_user_alter_zipreport_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverterdata',
            name='daily_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='inverter_daily_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='inverter_op_active_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='inverter_total_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='meter_active_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='op_active_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='specific_yields',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='total_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipreport',
            name='location',
            field=models.ManyToManyField(blank=True, to='adminapp.location'),
        ),
    ]
