# Generated by Django 4.0.4 on 2022-08-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_alter_inverterdata_daily_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='inverter_type',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
