# Generated by Django 4.0.4 on 2022-08-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_location_inverter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverterdata',
            name='normal_power',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
