# Generated by Django 4.0.4 on 2022-08-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_inverterdata_normal_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inverterdata',
            old_name='normal_power',
            new_name='nominal_power',
        ),
        migrations.AddField(
            model_name='inverterdata',
            name='alarm_date',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inverterdata',
            name='alarm_name',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inverterdata',
            name='alarm_ops_state',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inverterdata',
            name='alarm_status',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='manager',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
